const routes = {
    login: 'Login',
    signup: 'SignUp',
    main: 'Main',
    splash: 'Splash',
    editProfile: 'Edit Profile',
    dialog: "Dialog",
    news: "News",
    newsDetail: "NewsDetail",
    notification: "Notification",
    confirmRequest: "ConfirmRequest",
    menu: "Menu",
    account: "Account",
    publishFile: "PublishFile",
    scheduleUser: "ScheduleUser",
    scheduleCompany: "ScheduleCompany",
    scheduleList: "ScheduleListScreen",
    baseWebViewScreen: "BaseWebViewScreen",
    createSchedule: "CreateSchedule",
    revenue: "Revenue",
    ScheduleDetail: "ScheduleDetail",
    changePassword: "ChangePassword",
    adward: "Adward",
    workTypes: "WorkTypes",
    updateGuide: "UpdateGuide",
    appInfo: "AppInfo",
    personalMonthlyTarget: "PersonalMonthlyTarget",
    detailPerson: "DetailPerson",
    zoomImage: "ZoomImage",
    contact: "Contact", 
    personalPlan: "PersonalPlan",
    personalStrongAndWeakPoint: "PersonalStrongAndWeakPoint",
    personalQuarterTarget: "PersonalQuarterTarget",
    personalRevenueWarning: "PersonalRevenueWarning",
    resultView: "ResultView",
    createScheduleSale: "createScheduleSale",
    detailScheduleSale: "detailScheduleSale",
    select: "Select"
}

export default routes
